export type Project = {
  id: string;
  slug: string;
  title: string;
  description: string;
  technologies: string[];
  category?: string;
  createdAt?: string;
  demoUrl?: string;
  imageUrl?: string;
  logoUrl?: string;
  galleryUrls?: string[];
  outcome?: string;
  role?: string;
  sourceUrl?: string;
  sourceUrls?: { label: string; url: string }[];
  year?: string;
  teamSize?: number;
  frontendDeploy?: string;
  backendDeploy?: string;
};
